version: 2
jobs:
  docker-test1:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: docker-compose up -d
  docker-test2:
    machine: true
    steps:
      - checkout
      - run: docker-compose up -d  
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello" 
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths: echo-output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - docker-test1
      - docker-test2
      - one
      - two:
          requires:
            - one
